# Generated by Django 3.2.4 on 2021-06-27 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210627_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 27, 10, 39, 23, 278249), verbose_name='date published'),
        ),
    ]
